### ISSUE TITLE
Implement UserService

### ISSUE THREAD

**Issue by jinwoo1225** [jinwoo1225/random-dice#2]
- [x] ListUsers
- [x] #6
- [x] CreateUser
- [x]  #16 
- [x] #17

**Comment by NikhilSharma03** [comment]
The project seems interesting. Would love to contribute. 
Let me know if I can help 🤘 (if it's not a personal project).

**Comment by jinwoo1225** [comment]
Cool would you add get user handler? without an authentication. 😂

**Comment by jinwoo1225** [comment]
@NikhilSharma03 added you as collaborator in this repository ✌️ ez pz huh?

**Comment by NikhilSharma03** [comment]
> Cool would you add get user handler? without an authentication. joy

Got it. :laughing:

**Comment by NikhilSharma03** [comment]
One thing. Are we following any design pattern for folder structure which i should keep in mind?

**Comment by jinwoo1225** [comment]
add grpc handler on internal/server/handler/~~~_handler.go
add client(mongo, redis, ..) /client/~~~_client.go

no more or less 😄

**Comment by NikhilSharma03** [comment]
> add grpc handler on internal/server/handler/~~~_handler.go add client(mongo, redis, ..) /client/~~~_client.go
> 
> no more or less smile

Gotcha :+1:. Thank you

**Comment by NikhilSharma03** [comment]
Closing this one as it is completed :rocket:
